[workspace]
members = [
    "atomics",
    "buffer",
    "fastmetrics",
    "heatmap",
    "histogram",
    "logger",
    "metrics",
    "ratelimiter",
    "streamstats",
    "timer",
    "waterfall",
]
