[workspace]
members = [
    "atomics",
    "datastructures",
    "heatmap",
    "histogram",
    "logger",
    "metrics",
    "metrics2",
    "ratelimiter",
    "streamstats",
    "timer",
    "waterfall",
]
