[package]
name = "histogram"
version = "0.0.0"
edition = "2021"
authors = ["Brian Martin <bmartin@twitter.com>"]
license = "Apache-2.0"

[dependencies]
thiserror = "1.0.34"

[dev-dependencies]
criterion = "0.3.6"

[[bench]]
name = "bench"
harness = false
