[package]
name = "rustcommon-heatmap"
version = "0.1.1"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Heatmap datastructure for tracking distributions across a time window"
homepage = "https://github.com/twitter/rustcommon/heatmap"
repository = "https://github.com/twitter/rustcommon"

[dependencies]
crossbeam = "0.8.0"
rustcommon-atomics = { path = "../atomics" }
rustcommon-histogram = { path = "../histogram" }
thiserror = "1.0.20"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "heatmaps"
harness = false
