[package]
name = "rustcommon-metrics"
version = "2.0.0-alpha.0"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.8.0"
dashmap = "3.11.10"
rustcommon-atomics = { path = "../atomics" }
rustcommon-heatmap = { path = "../heatmap" }
rustcommon-streamstats = { path = "../streamstats" }
thiserror = "1.0.20"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "counters"
harness = false
