[package]
name = "rustcommon-metrics"
version = "1.0.0"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Metrics library"
homepage = "https://github.com/twitter/rustcommon/metrics"
repository = "https://github.com/twitter/rustcommon"

[dependencies]
dashmap = "3.11.4"
rustcommon-datastructures = { path = "../datastructures" }
serde = "1.0.110"
serde_derive = "1.0.110"
time = "0.1.42"
