[package]
name = "rustcommon-metrics-v2"
version = "0.1.0"
edition = "2018"
authors = ["Sean Lynch <seanl@twitter.com>"]
license = "Apache-2.0"

[dependencies]
linkme = "0.2.6"
parking_lot = "0.11.2"
rustcommon-metrics-derive = { path = "derive" }

